const express = require('express');
const dotenv = require('dotenv');
const { GoogleGenerativeAI } = require('@google/generative-ai');
const path = require('path');
const fs = require('fs');

// Load environment variables
dotenv.config();

const app = express();
const port = process.env.PORT || 3050;

// Logging configuration
const LOGS_DIR = path.join(__dirname, 'logs');
const ACTIVITY_LOG = path.join(LOGS_DIR, 'activity.log');
const ERROR_LOG = path.join(LOGS_DIR, 'error.log');

// Ensure logs directory exists
if (!fs.existsSync(LOGS_DIR)) {
    fs.mkdirSync(LOGS_DIR);
}

/**
 * Log activity to file
 */
function logActivity(message) {
    const timestamp = new Date().toISOString();
    const logEntry = `[${timestamp}] ${message}\n`;
    fs.appendFileSync(ACTIVITY_LOG, logEntry);
    console.log(`Activity: ${message}`);
}

/**
 * Log errors to file
 */
function logError(message, error) {
    const timestamp = new Date().toISOString();
    const stackTrace = error ? `\nStack: ${error.stack}` : '';
    const logEntry = `[${timestamp}] ERROR: ${message}${stackTrace}\n`;
    fs.appendFileSync(ERROR_LOG, logEntry);
    console.error(`Error: ${message}`, error);
}

// Initialize Google Generative AI
const apiKey = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY;
if (!apiKey) {
    logError('FATAL ERROR: GEMINI_API_KEY or GOOGLE_API_KEY not found in environment variables.');
} else {
    console.log(`API Key detected: ${apiKey.substring(0, 4)}...${apiKey.substring(apiKey.length - 4)}`);
}
const genAI = new GoogleGenerativeAI(apiKey);

// Middleware
app.use(express.json({ limit: '50mb' }));
app.use(express.urlencoded({ limit: '50mb', extended: true }));
app.use(express.static('public'));

/**
 * POST /api/generate
 * Extracts prompt, width, and height to generate an architectural plan description.
 * Note: Standard Gemini SDK currently specializes in text. 
 * For actual image generation, Imagen 3 via Vertex AI is typically used.
 * Here we simulate the reasoning/description process.
 */
app.post('/api/generate', async (req, res) => {
    try {
        const { prompt, width, height } = req.body;

        if (!prompt || !width || !height) {
            return res.status(400).json({ error: 'Missing required fields: prompt, width, height' });
        }

        // Use gemini-3.1-flash-image for actual image generation
        const model = genAI.getGenerativeModel({ 
            model: "gemini-3.1-flash-image-preview",
            generationConfig: {
                maxOutputTokens: 2048,
                temperature: 0.7
            }
        });

        const fullPrompt = `You are an expert architectural planner. 
        Generate a comprehensive TECHNICAL ARCHITECTURAL PLAN with specific dimensions: ${width}m x ${height}m.
        The plan should be a detailed top-down technical drawing.
        
        User Request Details: ${prompt}`;

        const result = await model.generateContent(fullPrompt);
        const response = await result.response;
        
        let imageUrl = '';
        let message = "Plan generated successfully.";

        // Find the image in the response parts
        const candidates = response.candidates;
        if (candidates && candidates[0].content.parts) {
            const imagePart = candidates[0].content.parts.find(part => part.inlineData);
            if (imagePart) {
                imageUrl = `data:${imagePart.inlineData.mimeType};base64,${imagePart.inlineData.data}`;
            }
            
            const textPart = candidates[0].content.parts.find(part => part.text);
            if (textPart) {
                message = textPart.text;
            }
        }

        if (!imageUrl) {
            throw new Error("No image was generated by the model.");
        }

        const usage = response.usageMetadata || { promptTokenCount: 0, candidatesTokenCount: 0 };
        const inputCost = (usage.promptTokenCount / 1000000) * 0.10;
        const outputCost = (usage.candidatesTokenCount / 1000000) * 0.40;
        const totalCost = inputCost + outputCost + 0.02;

        res.json({
            success: true,
            usage: {
                promptTokens: usage.promptTokenCount,
                completionTokens: usage.candidatesTokenCount,
                totalTokens: usage.totalTokenCount,
                estimatedCostUsd: totalCost.toFixed(6)
            },
            imageUrl: imageUrl,
            message: message
        });

        logActivity(`2D Image Generated: Prompt="${prompt}", Dim=${width}x${height}, Status=Success`);

    } catch (error) {
        logError(`Failed to generate 2D plan: ${error.message}`, error);
        res.status(500).json({ error: 'Failed to generate plan', details: error.message });
    }
});

/**
 * POST /api/generate-3d
 * Takes a base64 image of an architectural plan and generates 3D isometric views.
 */
app.post('/api/generate-3d', async (req, res) => {
    try {
        const { imageBase64 } = req.body;

        if (!imageBase64) {
            return res.status(400).json({ error: 'Missing base64 image data' });
        }

        // Clean up base64 string if it contains the data prefix
        const base64Data = imageBase64.replace(/^data:image\/\w+;base64,/, "");

        const model = genAI.getGenerativeModel({ 
            model: "gemini-3.1-flash-image-preview", // Using 2.0 Flash as placeholder for "gemini-2.5-flash-image"
            generationConfig: {
                maxOutputTokens: 2048,
                temperature: 0.8
            }
        });

        const perspectives = ["isometric front-right view", "isometric back-left view"];
        const results = [];
        let totalUsage = { promptTokenCount: 0, candidatesTokenCount: 0, totalTokenCount: 0 };

        for (const view of perspectives) {
            const prompt = `Based on this architectural plan, generate a high-quality 3D ${view} render of the house. 
            The render should be photorealistic, showing materials, lighting, and textures.`;

            const imagePart = {
                inlineData: {
                    data: base64Data,
                    mimeType: "image/png" // Assuming PNG, but could be dynamic
                }
            };

            const result = await model.generateContent([prompt, imagePart]);
            const response = await result.response;

            const candidates = response.candidates;
            if (candidates && candidates[0].content.parts) {
                const imgPart = candidates[0].content.parts.find(part => part.inlineData);
                if (imgPart) {
                    results.push(`data:${imgPart.inlineData.mimeType};base64,${imgPart.inlineData.data}`);
                }
            }

            // Accumulate usage
            const usage = response.usageMetadata || { promptTokenCount: 0, candidatesTokenCount: 0, totalTokenCount: 0 };
            totalUsage.promptTokenCount += usage.promptTokenCount;
            totalUsage.candidatesTokenCount += usage.candidatesTokenCount;
            totalUsage.totalTokenCount += usage.totalTokenCount;
        }

        if (results.length === 0) {
            throw new Error("Failed to generate any 3D perspectives.");
        }

        // Cost calculation for 3D generation (using 2.0 Flash rates as proxy)
        const inputCost = (totalUsage.promptTokenCount / 1000000) * 0.10;
        const outputCost = (totalUsage.candidatesTokenCount / 1000000) * 0.40;
        const imageGenFee = results.length * 0.02; // $0.02 per generated image
        const totalCost = inputCost + outputCost + imageGenFee;

        res.json({
            success: true,
            images: results,
            usage: {
                promptTokens: totalUsage.promptTokenCount,
                completionTokens: totalUsage.candidatesTokenCount,
                totalTokens: totalUsage.totalTokenCount,
                estimatedCostUsd: totalCost.toFixed(6)
            }
        });

        logActivity(`3D Model Generated: Perspectives=${results.length}, Status=Success`);

    } catch (error) {
        logError(`Failed to generate 3D model: ${error.message}`, error);
        res.status(500).json({ error: 'Failed to generate 3D model', details: error.message });
    }
});

app.listen(port, () => {
    console.log(`Server running at http://localhost:${port}`);
    
    // VPS/Production environment detection
    if (process.env.NODE_ENV === 'production') {
        logActivity('Server started in PRODUCTION mode.');
        console.log('VPS Environment detected. Ensure Cloudflare Tunnel is running.');
    } else {
        logActivity('Server started in DEVELOPMENT mode.');
    }
});
